---

- name: "configuration play." 
  hosts: all
  user: ubuntu
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml
  environment:
    ENVIRONMENT: production
    VERSION: 1
    TYPEORM_MIGRATIONS_DIR: "./src/migrations"
    TYPEORM_CONNECTION: "{{ ansible_env.TYPEORM_CONNECTION }}"
    TYPEORM_ENTITIES: "{{ ansible_env.TYPEORM_ENTITIES }}"
    TYPEORM_MIGRATIONS: "{{ ansible_env.TYPEORM_MIGRATIONS }}"
    TYPEORM_HOST: "{{ ansible_env.TYPEORM_HOST }}"
    TYPEORM_PORT: "{{ ansible_env.TYPEORM_PORT }}"
    TYPEORM_USERNAME: "{{ ansible_env.TYPEORM_USERNAME }}"
    TYPEORM_PASSWORD: "{{ ansible_env.TYPEORM_PASSWORD }}"
    TYPEORM_DATABASE: "{{ ansible_env.TYPEORM_DATABASE }}"
  roles:
    - deploy
