---

- name: "update apt packages"
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: "remove dependencies that are no longer needed"
  become: yes
  apt:
    autoremove: yes

- name: "install node"
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "install typescript interpreter"
  become: yes
  shell: pm2 install typescript

- name: "create directory"
  become: yes
  file:
    path: ~/project
    state: directory

- name: "copy backend code"
  become: yes
  copy:
    src: ~/project/backend
    dest: ~/project

